name: dancerang
description: DanceRang - Step into Excellence. A comprehensive dance studio management
  app for students, faculty, and administrators.
dependencies:
  cloud_firestore: ^6.0.3
  cloud_functions: ^6.0.3
  crypto: ^3.0.5
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  firebase_analytics: ^12.0.3
  firebase_auth: ^6.1.1
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.3
  firebase_messaging: ^16.0.3
  firebase_storage: ^13.0.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  http: ^1.2.2
  image_picker: ^1.0.4
  in_app_purchase: ^3.2.0
  path_provider: ^2.1.4
  pdf: ^3.11.3
  pinput: ^5.0.2
  printing: ^5.12.0
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  razorpay_flutter: ^1.3.7
  rxdart: ^0.28.0
  share_plus: ^12.0.0
  table_calendar: ^3.1.2
  timezone: ^0.10.1
  url_launcher: ^6.3.0
  video_player: ^2.9.2
  wakelock_plus: ^1.2.8
environment:
  sdk: ^3.8.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
